### PR TITLE
Generate participation maps per-county for the whole project & each normal code

### PR DESCRIPTION
**Pull request by as2388**
Some design decisions worth drawing your attention to:
- This uses geopandas for all map-related operations. Using QGIS’ API would have required building QGIS from source in a Docker container, which I chose not do.
- The geometry is currently committed to this project, because I expect it might change rapidly in the early weeks of automated mapping. However, it will probably want to move to Core Data once it stabilises. The geometry is included in GeoJson format rather than the shapefile format we’ve been using until now. GeoJson and shapefiles are interchangeable in QGIS, but geojson has the advantages of being human readable text rather than binary data (so better for version control, for example), and is self-contained in one file rather than split across 5 that need to have the same prefix and live in the same directory, at the cost of slightly increased disk usage.
- Text label locations are set using manually defined “label_x” and “label_y” co-ordinates in the GeoJson. I tried some automatic methods (centroid and polylabel) but these didn’t look as good. Those label positions can be set through a slightly painful manual process in QGIS, but I think a worthy trade-off for the quality of results given that we only need to do this once per map forever.

Sample outputs here: https://drive.google.com/drive/folders/1ejPWhZuyu8aK2rzwhS4VYrl4sJxvk2vd?usp=sharing 

Callouts, constituencies, lakes, coast lines etc. to come in future PRs.

### CODE REVIEW

**Comment by lukechurch** [comment]
@as2388 where does the geojson come from, and what licence is it under?

**Comment by lukechurch** [comment]
(I completely agree with manual location annotation per map)

**Review by lukechurch — APPROVED** [review]
LGTM subject to there not being a licence problem with the geodata

Thanks @as2388

**Review by IsaackMwenda — APPROVED** [review]
LGTM thanks @as2388 , with additional TODOS to add a north arrow https://stackoverflow.com/questions/58088841/how-to-add-a-north-arrow-on-a-geopandas-map at the bottom right and a legend

**Comment by as2388** [comment]
> @as2388 where does the geojson come from, and what licence is it under?

@IsaackMwenda will need to confirm where the counties map came from and its license. If the HDX, which is most likely, then, from a list of creative commons licenses, the one chosen is "Other: Humanitarian use only".

The more problematic case will be the constituency map. We've only found one source of an up-to-date map, from Kenya Open Data, whose license is "No License Specified". HDX constituency datasets are outdated.

**Comment by as2388** [comment]
> LGTM thanks @as2388 , with additional TODOS to add a north arrow https://stackoverflow.com/questions/58088841/how-to-add-a-north-arrow-on-a-geopandas-map at the bottom right and a legend

Thanks, will keep in mind that we may need these. However, we've not included them in CSAP for some time, so questionable as to how useful they are, so suggest leaving them until they're explicitly requested, or at least prioritising them below the things which have.

**Comment by lukechurch** [comment]
> > @as2388 where does the geojson come from, and what licence is it under?
> 
> @IsaackMwenda will need to confirm where the counties map came from and its license. If the HDX, which is most likely, then, from a list of creative commons licenses, the one chosen is "Other: Humanitarian use only".
> 
> The more problematic case will be the constituency map. We've only found one source of an up-to-date map, from Kenya Open Data, whose license is "No License Specified". HDX constituency datasets are outdated.

In which case we need to move them to something like 3rd party, list their licence (when we can) and where it is that we found then. Basically what we can't do is 'relicence' them as MIT by not talking about where they came from and putting them into a repo under MIT licence

**Pull request merged**
